import sys
import shutil
import subprocess
from mitim_tools.misc_tools import IOtools
from mitim_tools.transp_tools import NMLtools
from mitim_tools.transp_tools.utils import TRANSPhelpers
from mitim_tools.misc_tools.LOGtools import printMsg as print
from IPython import embed

"""
Runner for the TRANSP docker-lineage containers (v25.1.0+), which have NO singularity apps.
The workflow follows TRANSPhub (03_TRANSP_Containers/01_Docker_Containers/README.md):
source /opt/transp/environ, then pretr / trdat / label / copy_expert_for / tr_build.py,
run the linked executable, and trlook to produce the final CDF.

The same OCI image runs under different engines:
    - docker     (workstations; the image as provided, e.g. transp_v25.1.0:latest)
    - apptainer/singularity (clusters without docker, e.g. engaging; convert once with
      `apptainer build transp_v25.1.0.sif oci-archive://transp_v25.1.0_1.tar`)

This is the first implementation, meant for interactive/manual testing (blocking, local
execution inside the current allocation). Integration with mitim_job/MAESTRO comes later.
"""

def detect_engine():
    for engine in ["docker", "apptainer", "singularity"]:
        if shutil.which(engine) is not None:
            return engine
    raise RuntimeError("[MITIM] No container engine found in PATH (tried docker, apptainer, singularity)")


def write_commands_script(folder, runid, tok, mpisettings, nparallel):
    """
    Write the bash script executed INSIDE the container, with cwd = the run folder.
    Returns the script path. Also writes the pretr answers file (same answers as the
    singularity workflow: shot year code, confirm, comment, exit).
    """

    file_pre = folder / "pre_mitim"
    with open(file_pre, "w") as f:
        f.write("00\nY\nLaunched by MITIM\nx\n")

    txt_mpi = " MPI" if nparallel > 1 else ""

    if nparallel > 1:
        # MPI runs are single-node only (TRANSPhub known limitation).
        # --allow-run-as-root is required under docker (container user is root) and harmless under apptainer
        run_command = f"""echo "localhost slots={nparallel}" > machines
mpirun --allow-run-as-root -n {nparallel} -machinefile machines ./{runid}TR.EXE {runid} S"""
    else:
        run_command = f"./{runid}TR.EXE {runid} S"

    script = f"""#!/usr/bin/env bash
# TRANSP run script generated by MITIM (TRANSPdocker.py), executed inside the container.
# The docker-lineage images (v25+) ship no environment setup script, so this replicates the
# environment that the old singularity-app container exported (env of transp_23.1.sif),
# mapped onto the new versioned tree /opt/transp/vX.Y.Z (codesys and builds merged into one).

TR=$(ls -d /opt/transp/v* 2>/dev/null | tail -1)
echo "Using TRANSP tree: $TR"

export TRANSPROOT=$TR
export TRANSPHOME=$TR
export CODESYSDIR=$TR
export SC=$TR/csh
export SQ=$TR/qcsh
export SB=$TR/bin
export LOCAL=$TR
export BUILD=$TR
export XE=$TR/exe
export CONFIGDIR=$TR/config
export LOGDIR=$TR/log
export ADASDIR=/opt/adas
export PREACTDIR=/opt/preact
export NO_XTRANSPIN=TRUE
export PATH=$TR/exe:$TR/bin:$TR/qcsh:$TR/csh:$TR/tools:$PATH
for d in /opt/*/lib /opt/*/*/lib $TR/lib; do [ -d "$d" ] && LD_LIBRARY_PATH="$d:$LD_LIBRARY_PATH"; done
export LD_LIBRARY_PATH

# IMAS coupling: transp_local.rc sets IMAS_ON=1 and transp.rc then builds the IMAS link
# line from IMAS_PREFIX, which in the PPPL production environment comes from their IMAS
# module and is not defined anywhere in the image. Auto-detect the versioned install.
export IMAS_PREFIX=$(ls -d /opt/imas/* 2>/dev/null | tail -1)
export IMAS_HOME=$IMAS_PREFIX

# Build-time environment (compilers/linker flags used to link the run executable)
source $TR/transp_local.rc
source $TR/transp.rc

# Run-specific environment (self-contained under the run folder; note TRANSP uses TMPDIR_TR)
export WORKDIR=./
export RESULTDIR=$PWD/results
export DATADIR=$PWD/data
export TMPDIR_TR=$PWD/tmp
mkdir -p results data tmp

export NPROCS={nparallel}
export NBI_NPROCS={mpisettings["trmpi"]}
export NTOR_NPROCS={mpisettings["toricmpi"]}
export NPTR_NPROCS={mpisettings["ptrmpi"]}
export NGEN_NPROCS=0
export NCQL3D_NPROCS=0

# pipefail so that a failing step aborts the script even when piped into tee
set -eo pipefail

# Pre-processing
pretr {tok}{txt_mpi} {runid} < pre_mitim
trdat {tok} {runid} w q 2>&1 | tee {runid}tr_dat.log

# Link the run executable (what the old singularity "link" app did, but with tr_build.py
# instead of uplink, as TRANSPhub instructs for versions >= 23.2)
if [ ! -e {runid}TF.PLN ]; then csh $SC/label {runid}; fi
if [ ! -e {runid}ex.for ] && [ ! -e {runid}ex.f90 ]; then csh $SC/copy_expert_for {runid}; fi

# tr_build.py reads the pserve allocation from <target>_pserv.tmp, written by tr_start in
# the PPPL production system (not shipped in the containers). Generate it here: it selects
# the MPI vs serial makefile (max of the values) and the serial/parallel NUBEAM and PT_SOLVER
# library variants (nbi_pserve / nptr_pserve). The leading blank on each line is REQUIRED:
# datchk_mpi in TR.EXE re-reads this file skipping the first column (Fortran list-directed
# writes prepend one), and without it the names are read as "bi_pserve" etc. and it aborts.
cat > {runid}_pserv.tmp << EOF
 nbi_pserve = {mpisettings["trmpi"]}
 ntoric_pserve = {mpisettings["toricmpi"]}
 nptr_pserve = {mpisettings["ptrmpi"]}
EOF

# Target is the bare runid (no "tr" suffix): the makefile rule is `$(NAME): $(NAME)ex.o`
# with output $(NAME)TR.EXE, matching the {runid}ex.o that copy_expert_for produces.
tr_build.py trexe {runid}

# Run TRANSP
{run_command}

# Produce the final CDF in the working directory
csh $SC/trlook {tok} {runid}
"""

    file_script = folder / "mitim_transp_docker.sh"
    with open(file_script, "w") as f:
        f.write(script)

    return file_script


def run_transp_docker(
    folder,
    runid,
    tok,
    image=None,
    mpisettings={"trmpi": 1, "toricmpi": 1, "ptrmpi": 1},
    engine=None,
):
    """
    Run a complete TRANSP case from `folder` (must contain <runid>TR.DAT and UFILEs),
    blocking until it finishes. `image` is the docker tag (docker engine) or the path
    to the converted .sif (apptainer/singularity engine).
    """

    folder = IOtools.expandPath(folder)

    if engine is None:
        engine = detect_engine()

    if image is None:
        raise RuntimeError("[MITIM] No container image provided (docker tag or .sif path)")

    nparallel = max([1] + [int(v) for v in mpisettings.values()])

    # Same convention as TRANSPsingularity.defineRunParameters: 1 means "not used", exported as 0
    mpisettings = {k: (0 if int(v) == 1 else int(v)) for k, v in mpisettings.items()}

    # Point the namelist input paths (inputdir, solver templates) to the run folder, as
    # runSINGULARITY does via adaptNML at submission time — inputs copied from a previous
    # run carry stale absolute paths. nshot is read from the namelist itself (unchanged).
    nshot = IOtools.findValue(folder / f"{runid}TR.DAT", "nshot", "=")
    NMLtools.adaptNML(folder, runid, int(float(nshot)), str(folder))

    file_script = write_commands_script(folder, runid, tok, mpisettings, nparallel)
    log_file = folder / f"{runid}tr.log"

    if engine == "docker":
        container_command = f"docker run --rm -v {folder}:{folder} -w {folder} {image} bash {file_script.name}"
    else:
        # Bind the top-level folder, as in TRANSPsingularity (e.g. /pool001, /nobackup1, /orcd)
        start_folder = str(folder).split("/")[1]
        txt_bind = f"--bind /{start_folder} " if start_folder not in ["home", "Users"] else ""
        container_command = f"cd {folder} && {engine} exec {txt_bind}--cleanenv {image} bash {file_script.name}"

    print(f"\t- Running TRANSP ({runid}, {tok}) via {engine}, NPROCS = {nparallel}", typeMsg="i")
    print(f"\t- Log: {log_file}")

    with open(log_file, "w") as f:
        process = subprocess.Popen(
            container_command, shell=True, cwd=folder,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True,
        )
        for line in process.stdout:
            sys.stdout.write(line)  # live progress on screen (print is shadowed by printMsg, which takes no `end`)
            sys.stdout.flush()
            f.write(line)
            f.flush()
        process.wait()

    # --------------------------------------------------------------------------------------
    # Interpret outcome
    # --------------------------------------------------------------------------------------

    log_txt = log_file.read_text()

    if any(err in log_txt for err in TRANSPhelpers.CONTAINER_LAUNCH_ERRORS):
        raise RuntimeError(
            "[MITIM] The container failed to launch on this node (user namespace creation denied,"
            " check user.max_user_namespaces). TRANSP did not run"
        )

    cdf_file = folder / f"{runid}.CDF"
    if not cdf_file.exists():
        raise RuntimeError(
            f"[MITIM] TRANSP run did not produce {cdf_file.name} (exit code {process.returncode}), check {log_file.name}"
        )

    print(f"\t- TRANSP run finished, CDF produced: {cdf_file}", typeMsg="i")

    return cdf_file
