import sys
import shutil
import subprocess
from mitim_tools.misc_tools import IOtools
from mitim_tools.transp_tools.utils import TRANSPhelpers
from mitim_tools.misc_tools.LOGtools import printMsg as print
from IPython import embed

"""
Runner for the TRANSP docker-lineage containers (v25.1.0+), which have NO singularity apps.
The workflow follows TRANSPhub (03_TRANSP_Containers/01_Docker_Containers/README.md):
source /opt/transp/environ, then pretr / trdat / label / copy_expert_for / tr_build.py,
run the linked executable, and trlook to produce the final CDF.

The same OCI image runs under different engines:
    - docker     (workstations; the image as provided, e.g. transp_v25.1.0:latest)
    - apptainer/singularity (clusters without docker, e.g. engaging; convert once with
      `apptainer build transp_v25.1.0.sif oci-archive://transp_v25.1.0_1.tar`)

This is the first implementation, meant for interactive/manual testing (blocking, local
execution inside the current allocation). Integration with mitim_job/MAESTRO comes later.
"""

def detect_engine():
    for engine in ["docker", "apptainer", "singularity"]:
        if shutil.which(engine) is not None:
            return engine
    raise RuntimeError("[MITIM] No container engine found in PATH (tried docker, apptainer, singularity)")


def write_commands_script(folder, runid, tok, mpisettings, nparallel):
    """
    Write the bash script executed INSIDE the container, with cwd = the run folder.
    Returns the script path. Also writes the pretr answers file (same answers as the
    singularity workflow: shot year code, confirm, comment, exit).
    """

    file_pre = folder / "pre_mitim"
    with open(file_pre, "w") as f:
        f.write("00\nY\nLaunched by MITIM\nx\n")

    txt_mpi = " MPI" if nparallel > 1 else ""

    if nparallel > 1:
        # MPI runs are single-node only (TRANSPhub known limitation).
        # --allow-run-as-root is required under docker (container user is root) and harmless under apptainer
        run_command = f"""echo "localhost slots={nparallel}" > machines
mpirun --allow-run-as-root -n {nparallel} -machinefile machines ./{runid}TR.EXE {runid} S"""
    else:
        run_command = f"./{runid}TR.EXE {runid} S"

    script = f"""#!/usr/bin/env bash
# TRANSP run script generated by MITIM (TRANSPdocker.py), executed inside the container

# TRANSP environment of the container
pushd /opt/transp > /dev/null
source environ
popd > /dev/null

# Run-specific environment (self-contained under the run folder)
export RESULTDIR=$PWD/results
export DATADIR=$PWD/data
export TMPDIR=$PWD/tmp
mkdir -p results data tmp

export NPROCS={nparallel}
export NBI_NPROCS={mpisettings["trmpi"]}
export NTOR_NPROCS={mpisettings["toricmpi"]}
export NPTR_NPROCS={mpisettings["ptrmpi"]}

set -e

# Pre-processing
pretr {tok}{txt_mpi} {runid} < pre_mitim
trdat {tok} {runid} w q 2>&1 | tee {runid}tr_dat.log
label {runid}
copy_expert_for {runid}

# Build and link the final executable (this is what the singularity "link" app used to do)
tr_build.py trexe {runid}tr

# Run TRANSP
{run_command}

# Produce the final CDF in the working directory
trlook {tok} {runid}
"""

    file_script = folder / "mitim_transp_docker.sh"
    with open(file_script, "w") as f:
        f.write(script)

    return file_script


def run_transp_docker(
    folder,
    runid,
    tok,
    image=None,
    mpisettings={"trmpi": 1, "toricmpi": 1, "ptrmpi": 1},
    engine=None,
):
    """
    Run a complete TRANSP case from `folder` (must contain <runid>TR.DAT and UFILEs),
    blocking until it finishes. `image` is the docker tag (docker engine) or the path
    to the converted .sif (apptainer/singularity engine).
    """

    folder = IOtools.expandPath(folder)

    if engine is None:
        engine = detect_engine()

    if image is None:
        raise RuntimeError("[MITIM] No container image provided (docker tag or .sif path)")

    nparallel = max([1] + [int(v) for v in mpisettings.values()])

    # Same convention as TRANSPsingularity.defineRunParameters: 1 means "not used", exported as 0
    mpisettings = {k: (0 if int(v) == 1 else int(v)) for k, v in mpisettings.items()}

    file_script = write_commands_script(folder, runid, tok, mpisettings, nparallel)
    log_file = folder / f"{runid}tr.log"

    if engine == "docker":
        container_command = f"docker run --rm -v {folder}:{folder} -w {folder} {image} bash {file_script.name}"
    else:
        # Bind the top-level folder, as in TRANSPsingularity (e.g. /pool001, /nobackup1, /orcd)
        start_folder = str(folder).split("/")[1]
        txt_bind = f"--bind /{start_folder} " if start_folder not in ["home", "Users"] else ""
        container_command = f"cd {folder} && {engine} exec {txt_bind}--cleanenv {image} bash {file_script.name}"

    print(f"\t- Running TRANSP ({runid}, {tok}) via {engine}, NPROCS = {nparallel}", typeMsg="i")
    print(f"\t- Log: {log_file}")

    with open(log_file, "w") as f:
        process = subprocess.Popen(
            container_command, shell=True, cwd=folder,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True,
        )
        for line in process.stdout:
            sys.stdout.write(line)  # live progress on screen (print is shadowed by printMsg, which takes no `end`)
            sys.stdout.flush()
            f.write(line)
            f.flush()
        process.wait()

    # --------------------------------------------------------------------------------------
    # Interpret outcome
    # --------------------------------------------------------------------------------------

    log_txt = log_file.read_text()

    if any(err in log_txt for err in TRANSPhelpers.CONTAINER_LAUNCH_ERRORS):
        raise RuntimeError(
            "[MITIM] The container failed to launch on this node (user namespace creation denied,"
            " check user.max_user_namespaces). TRANSP did not run"
        )

    cdf_file = folder / f"{runid}.CDF"
    if not cdf_file.exists():
        raise RuntimeError(
            f"[MITIM] TRANSP run did not produce {cdf_file.name} (exit code {process.returncode}), check {log_file.name}"
        )

    print(f"\t- TRANSP run finished, CDF produced: {cdf_file}", typeMsg="i")

    return cdf_file
